Remove user table and move information to auth0
dotkom/monoweb pull request #1023
Opened 2024-09-24 16:17 UTC by jotjern

2024-09-24 16:55 UTC, junlarsen submitted a review, later dismissed
Didn't we agree on keeping the user table? @henrikhorluck 

Make it so the user table is a single column that has the auth0 subject in it? With the current changes it's very possible to lose references because there is no foreign key relations

2024-11-20 21:41 UTC, henrikhorluck requested changes

2024-11-20 21:41 UTC, henrikhorluck commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-card.tsx
> +        result.address = undefined
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete

2024-11-20 21:41 UTC, henrikhorluck commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +        placeholder: "12345678",
Dette eksempelet er ikke gyldig, og merk at for internasjonale må man ha med +xx

2024-11-20 21:41 UTC, henrikhorluck commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +        placeholder: "Ola",
Nordmann?

2024-11-20 21:41 UTC, henrikhorluck commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +          { label: "Annet", value: "other" },
Kan vi ha med "Ønsker ikke svare"?

2024-11-20 21:41 UTC, henrikhorluck commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +      rfid: createTextInput({
Jeg tror ikke dette er noe vi burde be brukere skrive selv, er litt jobb å dra frem NTNU-kortet, og vi bruker det ikke til noe atm

2024-11-20 21:41 UTC, henrikhorluck commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +      compiled: createCheckboxInput({
Jeg syntes dette er et felt Online skal styre og ikke brukeren selv, ser ikke poenget i at vi skal ha det som en bruker-styrt checkmark

2024-11-20 21:41 UTC, henrikhorluck commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +      address: createTextInput({
Jeg ville heller samlet inn adresse ved bestilling av noe i en (poentiensiell) nettbutikk. Dette bare samler data som vi ikke bruker til noe og har minimalt (for ikke si negativ! I tilfelle feilbestilling) for brukeren

2024-11-20 21:41 UTC, henrikhorluck commented on apps/dashboard/src/app/(dashboard)/user/[id]/page.tsx
> +        <Title>{user.firstName || user.lastName ? `${user.firstName} ${user.lastName}` : user.email}</Title>
Flytt denne logikken til brukeren?

2024-11-20 21:41 UTC, henrikhorluck commented on packages/auth/src/auth-options.ts
> +        await core.userService.registerId(token.sub)
Kan vi ikke bare kun ha `getById` som registrer selv? API-minimalisering

2024-11-20 21:41 UTC, henrikhorluck commented on packages/core/src/modules/user/user-repository.ts
> +  createDummyUser(data: UserWrite, password: string): Promise<User>
Dette virker 100% test-relatert og burde være i et annet API

2024-11-20 21:41 UTC, henrikhorluck commented on packages/core/src/modules/user/user-service.ts
> +  searchForUser(query: string, limit: number, offset: number): Promise<User[]>
Denne burde lenke til auth0 dokumentasjon over støttet syntax

2024-11-20 21:41 UTC, henrikhorluck commented on packages/db/src/db.generated.d.ts
> +  userId: string | null;
Hvorfor er alle disse satt som `| null`? Er det ment som `on delete set null`? Gir mer mening å slette hele privacy-objektet ved sletting/anonymisering.

Merk at vi i ow4 aldri sletter brukere—vi bare anonymiserer.

2025-01-21 09:22 UTC, jotjern commented on packages/db/src/db.generated.d.ts
> +  userId: string | null;
Generert fil som baserer seg på den lokale databasen, bare noe manuelt jeg hadde gjort som tulla det til.

2025-01-21 09:22 UTC, jotjern commented on packages/core/src/modules/user/user-service.ts
> +  searchForUser(query: string, limit: number, offset: number): Promise<User[]>
Jepp

2025-01-21 09:24 UTC, jotjern commented on packages/auth/src/auth-options.ts
> +        await core.userService.registerId(token.sub)
Blir et ekstra database-kall for hver gang vi skal hente en bruker da 🤔 jeg tenker det er greit sånn

2025-01-21 09:25 UTC, jotjern commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +      rfid: createTextInput({
Nei enig, dette er bare for å gjøre det mulig å se dataen i dashboardet, skal ikke be brukeren om det nå.

2025-01-21 09:26 UTC, jotjern commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +        placeholder: "Ola",
Word

2025-01-21 09:29 UTC, jotjern commented on apps/dashboard/src/app/(dashboard)/user/[id]/page.tsx
> +        <Title>{user.firstName || user.lastName ? `${user.firstName} ${user.lastName}` : user.email}</Title>
Tror dashboardet er det eneste stedet hvor vi har lyst til å bruke email som alternativ til navn 🤔 kan evt flytte til en utility function av noe slag...

2025-01-21 09:31 UTC, jotjern commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +      compiled: createCheckboxInput({
Dette er i dashboardet, ikke noe brukeren skal styre selv nei.

2025-01-21 09:33 UTC, jotjern commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-form.tsx
> +      address: createTextInput({
Enig. Fjerner

2025-01-21 09:56 UTC, jotjern commented on apps/dashboard/src/app/(dashboard)/user/[id]/edit-card.tsx
> +        result.address = undefined
Replaced with delete, but linter yells at it, so i reverted back to setting undefined.

2025-01-23 13:03 UTC, junlarsen approved these changes

2025-01-23 13:15 UTC, merged