Add vercel previews to allowed redirect urls in dev
dotkom/monoweb pull request #1038
Opened 2024-09-25 23:08 UTC by jotjern

2024-09-30 20:01 UTC, junlarsen approved these changes

2024-10-03 23:47 UTC, junlarsen commented
merge & apply @jotjern?

2025-03-12 20:42 UTC, junlarsen commented
Not applied yet I don't think. Just updated the branch to latest

2025-03-12 23:34 UTC, henrikhorluck requested changes
Hvorfor ikke bruke staging?

2025-03-13 00:06 UTC, henrikhorluck approved these changes

2025-03-13 11:36 UTC, merged