feat: define minimal event type for events
dotkom/monoweb pull request #168
Opened 2022-09-21 18:05 UTC by matsjla

Closes: None

## Checklist

- [ ] I have written tests
- [ ] I have provided documentation

## Changelog

- Minimal domain type

## How to test

No lol

2022-09-22 12:21 UTC, kharann commented on packages/ow-db/prisma/schema.prisma
> +model Event {
Probably be smart with a 

1. event status, such as Open event, Attendance event, Infinite slots, TBA (we have a lot of TBA events)
2. Eventually, relations to attendance, payment and the users (attendee)

2022-09-22 12:22 UTC, kharann commented
Honestly, Would be cool with template events in the future. Like a template for TBA events etc.

2022-10-20 21:44 UTC, kharann requested changes

2022-10-20 21:44 UTC, kharann commented on apps/ow-api/src/modules/event/attendance.ts
> +  deregirsterDeadline: z.date(),
```suggestion
  deregisterDeadline: z.date(),
```

2022-10-20 21:44 UTC, kharann commented
Also, thoughts on `eventId` vs `eventID`

2022-10-22 14:33 UTC, matsjla commented
I like eventId because eventID just looks weird :c

2022-10-22 14:34 UTC, kharann commented
f a i r

2022-10-22 14:39 UTC, kharann approved these changes

2022-10-22 14:39 UTC, merged