Marks
dotkom/monoweb pull request #211
Opened 2022-11-03 00:25 UTC by NjaalSoerland

Closes: #177 

## Checklist

- [x] I have written tests
- [ ] I have provided documentation

## Changelog

- Added schemas for marks and personal marks
- Created a repository and service for each of them
- Implemented functionality for creating marks, and adding and removing them from users
- Added functions for mark expiration calculation

## How to test

yarn test

2022-11-03 00:29 UTC, kharann commented
DATE FNS???

2022-11-03 00:39 UTC, NjaalSoerland commented
> DATE FNS???

Wip ;)

2022-11-15 17:47 UTC, kharann requested changes
Please convert the database models from prisma to the format with kysely.

Read #232 for the reasoning behind it. You can see in #235 how you create migrations etc.

You need to:
- rebase
- Convert schema to migrations in `ow-db`
- Convert repositories and test to use kysely
- Write database types in `ow-db`
-

2023-01-15 16:28 UTC, kharann requested changes

2023-01-15 16:28 UTC, kharann commented on packages/types/src/mark.ts
> +export type InsertMark = Omit<Mark, "id">
Call it MarkWrite

2023-01-15 16:28 UTC, kharann commented on packages/types/src/personal-mark.ts
> +export type InsertPersonalMark = PersonalMark
Rename to PersonalMarkWrite

2023-01-15 22:35 UTC, kharann commented on packages/api/src/modules/marks/mark-service.ts
> +      mark.givenTo.forEach(async (userId) => {
You could set the Mark to `ON DELETE CASCADE`, which will automatically delete all related marks when the given mark is deleted

2023-01-18 18:01 UTC, kharann approved these changes

2023-01-18 18:14 UTC, merged