Refactor all external sdks to be injected through dependency injection
dotkom/monoweb pull request #839
Opened 2024-03-12 20:52 UTC by junlarsen

2024-03-13 17:01 UTC, junlarsen commented
https://linear.app/dotkom/issue/DOT-635/establish-a-standard-way-of-handling-errors-for-the-internal-trpc-api

2024-03-17 17:44 UTC, henrikskog reviewed
Take a look at https://github.com/dotkom/monoweb/pull/839, I went ahead and looked at some of the things I found in the PR.

Btw, should we not do something like [this](https://trpc.io/docs/server/error-handling#handling-errors) in apps/web/src/pages/api/trpc/[trpc].ts?

2024-03-17 17:44 UTC, henrikskog commented on packages/core/src/modules/job-listing/job-listing-error.ts
I addressed this in https://github.com/dotkom/monoweb/pull/844, lmk what you think

2024-03-17 17:44 UTC, henrikskog commented on packages/core/src/modules/job-listing/job-listing-error.ts
> +    super("/problem/bad-request", 400, `The start date is invalid: ${reason}`)
Also addressed in https://github.com/dotkom/monoweb/pull/844

2024-03-18 07:38 UTC, junlarsen commented
I will handle tRPC specific stuff in a separate PR

2024-03-18 16:59 UTC, henrikskog requested changes
Really like this PR. What do you think about my comment?

2024-03-18 16:59 UTC, henrikskog commented on packages/core/src/error.ts
> +    super("/problem/illegal-state", 500, `Illegal state reached: ${description}`)
According to [the rfc](https://datatracker.ietf.org/doc/html/rfc9457#name-title) the title should not change for each occurance of the error

2024-03-20 17:56 UTC, merged