rename from email-gateway to brevdue
dotkom/monoweb pull request #843
Opened 2024-03-17 14:32 UTC by henrikskog

2024-03-17 14:33 UTC, henrikhorluck approved these changes

2024-03-17 14:33 UTC, junlarsen requested changes
call it brevduen

2024-03-17 16:17 UTC, henrikhorluck commented on docs/infrastructure/gateway-email.md
`Bredduen.md`?

2024-03-18 07:49 UTC, junlarsen approved these changes

2024-03-18 11:21 UTC, merged